### ISSUE TITLE
Question: automated tests

### ISSUE THREAD

**Issue by lucascebertin** [malucooo/otxserver-new#107]
Well, this is just a question about automated testing...
What you guys think about it?
IMHO, without tests is really hard to catch bugs early.

**Comment by favasconcelos** [comment]
IMO Yes, you are totally right, I thought about this a while ago. But since I don't have that much experience neither with lua or Can++, I didn't think more about it. Doing a bit of research on the lua side we could do something in terms of unit testing, using https://github.com/norman/telescope/ or some other framework.

**Comment by lucascebertin** [comment]
You're right considering cover Lua too, I totally missed that.
I was thinking to try the google unit test framework, they use it on some chromium projects.
But, anyway, this project is huge, I always think about the reverse enginnering related to the first emulator, for me it deserves automated testing to protect from bugs and regressions.
I will try to understand how things can play well together and good look for us on this journey.

**Comment by favasconcelos** [comment]
Also think that @malucooo or @newacc12 maybe have more insight about this or anyone with more contribution experience with the project itself.

**Comment by mattyx14** [comment]
@favasconcelos  im no have permission for a contribute here only check changes and set my oppinion if are good or bad the change. The project leader are @malucooo
