### ISSUE TITLE
weird packets sended to the server

### ISSUE THREAD

**Issue by Schiffers** [malucooo/Otxserver-New#156]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. login, open prey window
2. buy a reroll list
3. select an monster

### Expected behaviour
the bytes should be not sended to the server
### Actual behaviour
Player: Schiffer sent an unknown packet header: 0xeb!
Player: Schiffer sent an unknown packet header: 0xed!

### Environment
the only thing that I change was the line that show in the console what byte the players send

**Comment by Eternal-Scripts** [comment]
Invalid because the prey system its a script .lua (modules.lua) and not a cpp system.
These headers are registered in modules/modules.xml
Enabling in protocolgame.cpp the print will occurs that because these headers isn't in switch.
`<module type="recvbyte" byte="235" script="prey system/preysystem.lua" />
	<module type="recvbyte" byte="237" script="prey system/preysystem.lua" />`

**Comment by Schiffers** [comment]
sure, I understand the point! thanks for answer
