### ISSUE TITLE
Imbuing System Equipment

### ISSUE THREAD

**Issue by joseluis2g** [malucooo/Otxserver-New#162]
I think we would need a function like -while item is equipped- to make this system work like intended, the problem with the critical, ml, lifeleech stats cus elements are working fine or maybe something like registering all items as with the onDeEquip function.
what you guys think?

**Comment by westwol** [comment]
As I stated before, the current imbuement system only works with damage elements in weapons, still missing the skills, critical-mphp leech and protection against elements attributes. The easier way would be making a onEquip and onDeEquip script to assign those attributes as a CONDITION that must be removed using onDeEquip function but the fact that we will have to register every item with imbuementSlots is such a waste of time. So either we figure another way out or register hundreds of items in movements.xml.

**Comment by Schiffers** [comment]
Hello, my point about the critical, mp/hp leech is that we should add these skills and the others skills, also protections/increase damage to items 
attribute class, because with that we can handle more easily and have alot of differents combinations of the same item, exemple: I want to give critical attribute to any crossbow, but I want aswell give some protection, so I can handle with it directly in the item, and not applying with onEquip script, the item just exist with the attributes and the source will handle automatically...

**Comment by joseluis2g** [comment]
Ok was taking a shower and thinking on it and this is my solution, to create a new decay type that checks if item got imbuing slots and if got time left, with that we can easily add attributes to the imbuiment items that will only work when you got it equipped and will stop working when time is over or when you deequip it.
this is very much similar to what @Schiffers thinks, ofc this will require source changes.

**Comment by westwol** [comment]
@Schiffers Imbuement items have duration and the attributes must be removed once the time is up.

**Comment by Schiffers** [comment]
@westwol we can handle with it in c++ as DECAY_STATE is treated, but in our case instead remove the item we remove the attributes and the decay state, or we can just create another item with same id/name without the attributes

**Comment by westwol** [comment]
I might start working on this if I achieve something I will let you know guys.

**Comment by joseluis2g** [comment]
I think this should be sources related, using something like custom item attributes adding and removing stats when you equip them would be easy, then you can check the remaining time creating a new internal decay that would remove the item custom attribute and transforming it to the same item but w/o attributes and that way we could remove the player stats

**Comment by Schiffers** [comment]
My idea to create the attributes for skills is nice, as I said the server will handle automatically with add/remove attribute when the time is over, but about the equip and deEquip I agree with @joseluis2g, we should make everything related to it in c++

**Comment by joseluis2g** [comment]
ok guys I got something working, when im back at home I gonna post it, its just lua and its not very beauty to be honest but is working

**Comment by joseluis2g** [comment]
I got a script working but I want some advices about it, what you guys think? @Schiffers, @Eternal-Scripts, @westwol.

**Comment by Schiffers** [comment]
@joseluis2g Hi!, if I can help let me help :)

**Comment by joseluis2g** [comment]
btw you have to do some changes on imbuiment file to solve some bugs

**Comment by Schiffers** [comment]
yes, my imbuement atm is "bugged" don't apply the changes in the items, also crash the server when try imbue the same slot but all time it still "empty" and onLook don't get any imbuement just "empty slot"

**Comment by Eternal-Scripts** [comment]
@joseluis2g add me skype i have advice in prey system lets go work in group.
Skype: eternal.scripts

**Comment by Schiffers** [comment]
I send invite to you @Eternal-Scripts, @joseluis2g post your skype

**Comment by joseluis2g** [comment]
gonna add you bro

**Comment by joseluis2g** [comment]
sadly I cant do this now, but tomorrow. My email is joseluis.ggr@gmail so my skype (I guess).
By the way, thanks again @Eternal-Scripts, you made this.

**Comment by joseluis2g** [comment]
btw something that I have notice is when you apply the imbuiment and it fails it doesnt send the message with the new count items, maybe if imbuing fails it should close the window, just my opinion.

**Comment by Eternal-Scripts** [comment]
I fixed prey system now and tested in Flash Client | 11.0 | 10.0 and is working fine (all bug's fixed).
The only step where is missing is:
- **Bonus Reroll**

because when u request bonus reroll he give you a list where u can re-select and not use the same monster  and random bonus.

Structure Prey System:
![screenshot_1](https://cloud.githubusercontent.com/assets/20959344/26527575/e5617dde-436c-11e7-8bf6-df7de5bb32bd.png)

**Extra Information**
Column 1 sends byte 0
Column 2 sends byte 1
Column 3 sends byte 10 (wtf)

Now about imbuing is correct but the actual **PRIORITY** problems is:
❌  Missing icon id's for all efects (11.0 feature)  
❌  Vector & merge of effects to generate list im imbuement (need to make this work to 1 ~ 3 slots!)

Isn't so hard to make this, only two steps to finish the part of imbuing shrine.

**Comment by Schiffers** [comment]
**Column 3 sends byte 10 (wtf)**
binary language 1+1 = 10 haha

**Comment by joseluis2g** [comment]
@Eternal-Scripts thats awesome, whats is missing for those icon ids? havent seen those changes yet,
gonna add you after launch and gonna send you my imbuiment idea script.
