### ISSUE TITLE
Client crash on change outfit

### ISSUE THREAD

**Issue by gonsandia** [malucooo/Otxserver-New#210]
![error](https://user-images.githubusercontent.com/8087716/27322378-3b2fef3c-559e-11e7-93ab-951d26d63c23.png)

**Comment by joseluis2g** [comment]
can you show your outfits file pls? Also what version are you using?

**Comment by gonsandia** [comment]
I just download this repo
https://github.com/malucooo/Otxserver-New/blob/master/data/XML/outfits.xml
https://github.com/malucooo/Otxserver-New/blob/master/src/outfit.cpp
https://github.com/malucooo/Otxserver-New/blob/master/src/outfit.h
and the client I download version 10.100

**Comment by malucooo** [comment]
using wrong client... in readme have a link!!!

**Comment by kreamkul** [comment]
But with readme client i cant login.

**Comment by darkjav** [comment]
You need use client 10, not 11.

**Comment by joseluis2g** [comment]
client 11 is not working? why?

**Comment by darkjav** [comment]
Client 11 working good, but there not exist new outfits, so this crash.

For the new outfits we need bytes for client 11.30

**Comment by joseluis2g** [comment]
ok actually there arent much changes, 
gonna listen it now:

- 3 new bytes: we send two to the client (99 called client check and 155 called blessings dialog) and we recieve back one byte (207 from bless dialog)
- bless status now recieve 3 values instead of 2
- something added on ondeath windows, very wierd atm cus im really tired
- 2 type of summons, player summons or other summons aka monsters

hope that helps, maybe gunzino could help you guys.
