### ISSUE TITLE
Critical Hit error

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#258]
I look that players with equipment critical weapon, example:  blade of mayhem (overcharged), only get critical hit when they use spells attack, and not with normal attack.

**Comment by westwol** [comment]
Taking a look to the code that triggers critical hit, it was moved to player and combat. I haven't had any issue handling it through game.cpp in Game::combatHealthChange as life and mana leech do.

**Comment by jlcvp** [comment]
@westwol the problem is that combatHealthChange would be called to each monster, though, every one would have the chance to apply critical or not (the rand would be calculated separately for each monster). This bug is already described on mattyx14/otxserver#252 and a discussion on how to fix it is held there too.

**Comment by jlcvp** [comment]
this is still present, reopening issue

**Comment by darkjav** [comment]
@jlcvp 
I think that one part of issue was fixed with this: https://github.com/malucooo/Otxserver-New/commit/b5bee499b4f42ee6d94a851e28c2c91bebcfce68
