### ISSUE TITLE
Melee weapons can't destroy spider web.

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#368]
Melee weapons (sword, club, axe) can't destroy spider webs, only the firebug is working.

**Comment by RafaelPereiraa** [comment]
That's because the "destroyto" attribute of items on items.xml are missing... If you check on the TFS stock items.xml, there are 91 items that has informations like:

`<item id="1614" article="a" name="big table">
		<attribute key="destroyTo" value="2253" />
	</item>`

While the Otx have only:

`<item fromid="1602" toid="1614" article="a" name="big table" /> `

That's just an example... the webs and everything else that can be broken are missing this. I would like to contribute here, but i don't know how to work with git. :(

**Comment by RafaelPereiraa** [comment]
Hello, @sn4tch0vsk 

Download the items.xml i uploaded here [items.txt](https://github.com/malucooo/Otxserver-New/files/1216821/items.txt) (remind to exchange the extension to .xml) 

Replace yours "data\actions\lib\actions.lua" by this [actions.lua](https://pastebin.com/JP55mzt4)

And yours "data\actions\scripts\other\destroy.lua" by this [destroy.lua](https://pastebin.com/2ZY0tJnY)

It should work fine to weapons wont working on breaking things, etc. :)

@malucooo take a look here when you have some time, please.

**Comment by mattyx14** [comment]
I update it tomorrow

**Comment by sn4tch0vsk** [comment]
Thanks @mattyx14 @RafaelPereiraa

**Comment by RafaelPereiraa** [comment]
Here's my latest [Actions.lua](https://pastebin.com/V6Fq8ixP), there should be some little tweaks to be done,... i tried my best.
This one already have the correct Against The Spider Cult Eggs configured, as also the chance for spawning spiders/poison/tarantulas on the normal ones. 

I hope I've helped.

Good night guys, and see you on the next week.
