### ISSUE TITLE
The correct way to run the server -Fix Command

### ISSUE THREAD

**Issue by Zainox** [malucooo/Otxserver-New#51]
I have got the solution, the problem covered in the way the console window is run in linux, here is the solution for people who have the stability problem in Linux:

I created a dedicated screen which can anytime be resumed

if you dont got "screen" install it: apt-get install screen

create otserv screen:
screen -A -S otserv

run OT ./forgottenserver
leave screen: CTRL + A + D (in this order)

to enter screen again in a later moment:
screen -x otserv

to start with auto-restarter:
while true; do ./theforgottenserver; done

To view already-created screens:
screen -ls (dont do this inside a screen)

keep in mind: avoid making multiple screens of same name. So always make sure to verify that the screen dont exist before creating it. Else things will easily get confusing.

**Comment by newacc12** [comment]
Are you referring to https://github.com/malucooo/Otxserver-New/issues/12 ? I've never had that problem again so I don't really know what could've caused it. I haven't changed any sources since that day. So you are saying if we use screens we wouldn't get the crashes anymore?

**Comment by esbuma** [comment]
after u use the auto restart...how can u stop it?

**Comment by darkjav** [comment]
Well, I would not call it a solution, rather this is the correct way to run the server on Linux. So doing it like this, nobody has to have problems. If they do differently it, is obvious that the server will be closed, since when the console session expires or when close the window, the process go to finished.

@ malucoo You can close this topic, or leave it open for others to see and know the correct way to run the server. :smiley:

**Comment by Zainox** [comment]
@darkjav yeah, you have reason, and @esbuma in this command have the autorestarter
