### ISSUE TITLE
Erros ao compilar no linux (ultimos commits)

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#599]
![image](https://user-images.githubusercontent.com/31714466/31853269-8f9db53c-b664-11e7-838c-8fec12824113.png)

Deu esse erro ao tentar compilar o clone do git de voces no linux, incrivel que eu baixo o clone de voces, testo e reporto os bugs, e fica vai apenas pra "closed" mesmo sem ter sido resolvido :P

**Comment by mattyx14** [comment]
u need install luajit lib

**Comment by EnzzoCaaue** [comment]
I'm pretty sure you haven't installed libs so stop with that bullshit.

**Comment by LudoEducativo** [comment]
Olá @Xiolonesz. Creio que esteja faltando uma biblioteca para que você compile devidamente a Godot. Entretanto o report de issues não é para receber mais de uma issue repetida e também não existe para ser dado suport a compilação da ferramenta. Veja, é muito importante ler o que lhe responderam (caso entenda Inglês) e então não replicar coisas de suporte como Issues.

Certamente o pessoal agradeçe sua colaboração, entretanto recomendo que entre em contato ou pesquise devidamente antes de postar algo como uma Issue, sendo que a maioria dos posts aqui são diretamente relacionados ao desenvolvimento da ferramenta, não à uso ou suporte a compilação.

A, creio que não hajam muito desenvolvedores chave que falem Português então, se possível, sempre tente mandar uma mensagem em Inglês, para que eles lhe entendam :D

Agradeço a compreensão ^_^

----------------------------------------------------------------------------------------------------------------

Hello @Xiolonesz. I believe that there's a missing library for you to successfully compile Godot. But issue report shouldn't receive doubled issues and also shouldn't serve as support feature for those who want to compile the tool. Look, it's very important read what they answered you (if you understand English) and don't replicate support related things as Issues.

Certainly all of us thank you for your collaboration, but I recommend you contact or search properly before posting something as an Issue, since the majority of posts here are related to the direct development of the tool, not to usage/compilation support.

Oh, I believe that not many key developers speak Portuguese so, if possible, try to always send messages in English, so that they can understand you :D

Thank you for comprehending the situation.

**Comment by Marcelo-Petrucelli** [comment]
Olá @Xiolonesz. Creio que esteja faltando uma biblioteca para que você compile devidamente a Godot. Entretanto o report de issues não é para receber mais de uma issue repetida e também não existe para ser dado suport a compilação da ferramenta. Veja, é muito importante ler o que lhe responderam (caso entenda Inglês) e então não replicar coisas de suporte como Issues.

Certamente o pessoal agradeçe sua colaboração, entretanto recomendo que entre em contato ou pesquise devidamente antes de postar algo como uma Issue, sendo que a maioria dos posts aqui são diretamente relacionados ao desenvolvimento da ferramenta, não à uso ou suporte a compilação.

A, creio que não hajam muito desenvolvedores chave que falem Português então, se possível, sempre tente mandar uma mensagem em Inglês, para que eles lhe entendam :D

Agradeço a compreensão ^_^

Hello @Xiolonesz. I believe that there's a missing library for you to successfully compile Godot. But issue report shouldn't receive doubled issues and also shouldn't serve as support feature for those who want to compile the tool. Look, it's very important read what they answered you (if you understand English) and don't replicate support related things as Issues.

Certainly all of us thank you for your collaboration, but I recommend you contact or search properly before posting something as an Issue, since the majority of posts here are related to the direct development of the tool, not to usage/compilation support.

Oh, I believe that not many key developers speak Portuguese so, if possible, try to always send messages in English, so that they can understand you :D

Thank you for comprehending the situation.
