### ISSUE TITLE
Bug in Annihilator quest/Demon outfit NPC

### ISSUE THREAD

**Issue by H0ltman** [malucooo/Otxserver-New#773]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Talk to NPC Avar Tar.
2. Get demon outfit. Then beat Annihilator.
3. You cannot claim reward chests "chest is empty".

### Expected behaviour
You should be able to do both.

### Actual behaviour
You can only do one.

**Comment by OBUCHpl** [comment]
Acording to Avar Tar.lua:
"if player:getStorageValue(Storage.AnnihilatorDone) == 1 or player:getStorageValue(2216, 1) then" 
you cannot receive outfit without having annihilator quest done. However there is strange storage value 2216 which I can't find anywhere. What is more, in door.lua (annihilator quest folder) in line 2 there should be "< 1" instead of "~= 1" because of the fact that after obtaining outfit your storage value is 2 and you are allowed to pass the door once again. Maybe you have done annihilator once, then after receiving outfit you tried to do annihilator once again, so the chest was empty?

**Comment by malucooo** [comment]
Fixed at last commit
